name: CI

on: [push]

jobs:
  build:
    name: Build

    runs-on: macOS-latest

    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,name=iPhone Xs'

    steps:
     - uses: actions/checkout@v1
     - name: Instal xcodegen
       run: brew install xcodegen
     - name: Run tests
       env:
         destination: ${{ matrix.destination }}
       run: |
         make test destination="${destination}"
     - name: Send coverage data
       if: success()
       env:
         CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
       run: |
         make send-coverage-report-to-codeclimate GIT_BRANCH=$GITHUB_REF GIT_COMMIT_SHA=$GITHUB_SHA
